extraction_task:
  description: >
    Raw Report: {raw_report}
    
    Carefully analyze the raw medical notes provided.
    Extract and categorize all relevant information according to the following sections:
      1. Patient information (name, age, gender, weight, etc.)
      2. Medical history (personal and family)
      3. Clinical presentation (current symptoms and observations)
      4. Physical examination (results of clinical examination)
      5. Additional examinations (test and analysis results)
      6. Diagnosis and treatment (including differential diagnoses)
      
    For each section, clearly identify if information is missing
    Point out the missing information in the report.
    Don't add any information to the report, just extract the information.
  expected_output:
    A structured document containing the extracted information, organized by section.
    Each section should contain all relevant information found in the notes.
    For sections without information, explicitly indicate "Information not provided.
  agent: extracting_agent
  output_file: Reports/1-Extraction/extraction

structuring_task:
  description: >
    Organize the extracted information according to a structure appropriate for a medical document.
    Respect the standard hierarchy of documents (sections, subsections).
    Structure to be followed:
      1. Patient information (section)
      2. Medical history (section)
      - Personnel (subsection)
      - Family (subsection)
      3. Clinical presentation (section)
      4. Physical Exam (section)
      5. Additional examinations (section)
      6. Diagnosis and treatment (section)
      - Main diagnosis (subsection)
      - Differential diagnoses (subsection)
      - Treatment plan (subsection)

    For sections without information, provide a clear indication in the structure.
      Don't add any information to the report, just extract the information.
  expected_output: >
    A detailed structure of the document, with hierarchical organization of sections and sub-sections, and the elements that will require special formatting.
  agent: structuring_agent
  output_file: Reports/2-Structuring/structuring
  context:
    - extraction_task

writing_task:
  description: >
    Transform structured information into a coherent, precise and concise medical text.            
    
    Use clear language while maintaining the necessary scientific rigour.
    Clearly identify the important information to be highlighted.
    Respect the structure defined above.
    Avoid excessive medical jargon except where necessary for accuracy.
    For each section, write a clear and complete paragraph, or indicate explicitly 
    the lack of information.
            
    For sections without information, provide a clear indication in the structure.
      Don't add any information to the report, just extract the information.
  expected_output: >
    The complete textual content of the medical report, organized according to the defined structure, with clear indications on the elements to highlight in the document.
  agent: writing_agent
  output_file: Reports/3-Writing/writing
  context:
    - structuring_task

validation_task:
  description: >
    Review the contents of the report for clinical inconsistencies or medical errors.
      Check consistency between:
      - The symptoms described and the proposed diagnosis
      - Review results and conclusions
      - The established diagnosis and differential diagnoses considered
      
      Ensure that medical terminology is used correctly.
      Verify that critical information is properly identified for highlighting.
      Verify that the level of detail is appropriate for a professional medical report.

      Beside medical errors or inconsistencies, do not add any information to the report, patient's information are usually missing.
  expected_output: >
    A validation report detailing:
      1. If the content is clinically consistent and accurate
      2. Any errors or inconsistencies detected
      3. Suggestions for correction if necessary

  agent: validation_agent
  output_file: Reports/4-Validation/validation
  context:
    - writing_task

correction_task:
  description: >
    Receive the medical report content generated by the writing agent, along with the validation review.

    Based on the validation results:
      - Apply all necessary corrections to eliminate clinical inaccuracies or inconsistencies.
      - Ensure that the medical reasoning is coherent across all sections (symptoms, findings, diagnosis, treatment).
      - Adjust terminology to maintain scientific precision and professional clarity.
      - Respect the original structure of the document as defined in the writing and structuring phases.
      - Ensure that all important medical details are clearly highlighted when relevant.

    For any sections or subsections where data is incomplete or missing, insert a clear note:
      - "This information is classified" for restricted, confidential or absent content.
  expected_output: >
    A corrected and finalized version of the medical report, aligned with the structure defined earlier, free of medical inconsistencies or errors, and clearly indicating missing or classified information where applicable.
    Do not add any information to the report, just extract the information, and correct the medical errors.
  agent: correction_agent
  output_file: Reports/5-Correction/corrected_report
  context:
    - writing_task
    - validation_task


latex_task:
  description: >
    Turn content into a complete and properly formatted LaTeX document, including each information in the appropriate section.  
    The document must:
      1. Use the 'article' class with appropriate packages for medical documentation
      2. Include a full preamble with the necessary packages
      3. Structure content according to LaTeX standards (section, subsection, etc.)
      4. Highlight important information
      5. Use specific environments for different parts of the report
      6. Leave blank sections without information, with the mention "This information is classified"

    The LaTeX code must be complete and ready to be compiled without further modification.
    (write latex directly without ```latex at the beginning and ``` at the end of the document)

  expected_output: >
    A complete LaTeX document ready for compilation.
    In the latex document, use the following template to fill in the necessary information
    If you don't have the information, leave "This information is classified".
    
            \documentclass[12pt][article]
            \usepackage[a4paper, margin=1in][geometry]
            \usepackage[graphicx]
            \usepackage[titling]
            \usepackage[fancyhdr]
            \usepackage[setspace]
            \usepackage[titlesec]
            \usepackage[lmodern]
            \usepackage[parskip]
            \usepackage[datetime]
            \usepackage[tikz]

            \pagestyle[fancy]
            \fancyhf[]
            
            \fancyhead[L][DocCrew Medical Center]
            \fancyhead[R][Dr. Yahya Ghallali]
            
            \fancyfoot[C][\thepage]
            \fancyfoot[L][]
            \fancyfoot[R][]


          \renewcommand[\baselinestretch][1.3]
          \titleformat[\section][\normalfont\large\bfseries][\thesection.][1em][]

          \begin[document]
          
            %=======================
            % PAGE 1: COVER
            %=======================
          \begin[titlepage]
              \begin[center]
                  \vspace*[1cm]
          
                  % Logo
                  \includegraphics[width=0.5\textwidth, height=0.5\textwidth]{clinic-logo.png}\\[1cm] % Replace with actual file
          
                  % Clinic Name
                  [\LARGE \textbf[DocCrew Medical Center]\\[0.5em]]
                  [\large ENSET Mohammedia]\\
                  [\large Phone: +212 661 123 45 67 | Email: info@DocCrewClinic.com]\\
          
                  \vspace[2cm]
          
                  [\Huge \textbf[Medical Report]\\
          
                  \rule[\textwidth][0.4pt]\\[0.5cm]
                  \vspace[0.5cm]
          
                  % Patient Information Box
                  \begin[flushleft]
                  [\Large \textbf[Patient Information]\\[0.5em]]
                  \begin[tabular][rl]
                      \textbf[Name:] & This information is classified \\
                      \textbf[Age:] & patient_age years \\
                      \textbf[Sex:] & patient_sex \\
                      \textbf[Patient ID:] & patient_id \\
                      \textbf[Date of Report:] & \today \\
                  \end[tabular]
                  \end[flushleft]
          
                  \vfill
          
                  \begin[flushright]
                      \textit[Prepared by: Dr. Yahya Ghallali]\\
                      \textit[License SDIA]\\
                  \end[flushright]
              \end[center]
          \end[titlepage]
          
          %=======================
          % PAGE 2: MEDICAL CONTENT
          %=======================
          \section*[Medical History]
          Brief summary of relevant past medical conditions, surgeries, allergies, and family history.
          
          \section*[Clinical Presentation]
          Current symptoms and clinical observations.
          
          \section*[Investigations]
          Lab tests, imaging, or other diagnostic results.
          
          \section*[Diagnosis and Treatment]
          Final diagnosis, recommended treatment, and medications.
          
          \vfill
          
          \begin[flushright]
          \textit[Signature: \rule[4cm][0.5pt]\\
          \textit[Date: \today]
          \end[flushright]
          
          \end[document]


          Ensure that the latex document is complete and ready to be compiled without further modification and with correct latex syntax
  agent: latex_agent
  output_file: Reports/6-LatexReport/report.tex
  context:
    - correction_task
